#!/bin/bash

# --------------------------------------------------------------
# Every text file here is returned to your kata after a test run, and
# mockgen writes one file for each interface it mocks. Those are written
# again from scratch on the next run, so an edit to one would be thrown
# away; they are removed here rather than handed back to you.
#
# What is matched is the line mockgen puts at the top of every file it
# writes, so a file of your own is never removed, whatever you name it.
source ~/cyber_dojo_fs_cleaners.sh
function cyber_dojo_exit()
{
  # Only .go files are read. This file has to hold the line being searched
  # for, and reading only .go files is what stops it deleting itself.
  #
  # Short flags because grep here is busybox, which has none of the long
  # spellings: -l names the files rather than the matching lines, -s stays
  # quiet about a file it cannot open, -F takes the pattern literally.
  # /dev/null gives grep a file to read when you have no .go files at all;
  # with no file at all it would sit waiting on its input.
  shopt -s globstar nullglob
  cyber_dojo_delete_files $(grep -l -s -F \
    'Code generated by MockGen. DO NOT EDIT.' **/*.go /dev/null)
}
trap cyber_dojo_exit EXIT SIGTERM

# --------------------------------------------------------------
# There is no internet access here, so go must not go looking for
# go.uber.org/mock. Everything it needs is already in this container.

# Do not contact a module proxy to download or resolve a module.
export GOPROXY=off
# Do not check a module's checksum against the public checksum database.
export GONOSUMDB='*'
# Packages compiled once when this container's image was built. Reusing them
# is what makes a test run quick; without it every run recompiles gomock.
export GOCACHE=/go/build-cache

# --------------------------------------------------------------
# mockgen writes the mock for an interface. It runs once for each
# //go:generate line, so an interface of your own gets a mock as soon as you
# put such a line above it. hiker.go has one to copy.
#
# Both commands walk every directory below this one, so a file you put in a
# sub-directory has its mocks written and its tests run too.
#
# go recognizes a test file by its name ending _test.go, so a test in a file
# named anything else will not run.
GO_TEST_OPTS=()
GO_TEST_OPTS+=(-v)        # name each test as it runs, so you can see which ran
GO_TEST_OPTS+=(-count=1)  # run them every time, not reprint an earlier result

go generate ./... && go test "${GO_TEST_OPTS[@]}" ./...
